In [1]:
import numpy as np

# Create two 3x3 matrices with random integers between 0 and 10 (inclusive)
matrix_a = np.random.randint(0, 11, size=(3, 3))
matrix_b = np.random.randint(0, 11, size=(3, 3))

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)

# Perform matrix operations
matrix_sum = matrix_a + matrix_b
matrix_difference = matrix_a - matrix_b
matrix_product = np.dot(matrix_a, matrix_b) # or matrix_a @ matrix_b

print("\nMatrix A + Matrix B:\n", matrix_sum)
print("\nMatrix A - Matrix B:\n", matrix_difference)
print("\nMatrix A * Matrix B:\n", matrix_product)

# Compute determinant, inverse, and rank of Matrix A
determinant_a = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:", determinant_a)

# Check if the matrix is invertible before computing the inverse
if np.linalg.det(matrix_a) != 0:
    inverse_a = np.linalg.inv(matrix_a)
    print("\nInverse of Matrix A:\n", inverse_a)
else:
    print("\nMatrix A is singular and does not have an inverse.")

rank_a = np.linalg.matrix_rank(matrix_a)
print("\nRank of Matrix A:", rank_a)

Matrix A:
 [[ 1  7  5]
 [ 7  0  9]
 [ 9 10  3]]

Matrix B:
 [[ 9  2  5]
 [ 9  6  5]
 [10  6  9]]

Matrix A + Matrix B:
 [[10  9 10]
 [16  6 14]
 [19 16 12]]

Matrix A - Matrix B:
 [[-8  5  0]
 [-2 -6  4]
 [-1  4 -6]]

Matrix A * Matrix B:
 [[122  74  85]
 [153  68 116]
 [201  96 122]]

Determinant of Matrix A: 679.9999999999998

Inverse of Matrix A:
 [[-0.13235294  0.04264706  0.09264706]
 [ 0.08823529 -0.06176471  0.03823529]
 [ 0.10294118  0.07794118 -0.07205882]]

Rank of Matrix A: 3
